### ISSUE TITLE
[FR]: Style settings for background color and heading level

### ISSUE THREAD

**Issue by etiennepellegrini** [imshenshen/obsidian-sticky-heading#6]
Would it be possible to add the headings' background color to the Style plugin settings?
Right now it's using `--titlebar-background`, but I would prefer to revert it to `--background-primary`

Another setting I'd like to have is the possibility to hide the heading levels, or change their style. Out of the box, the conflict with my line numbers.

I created the following css snippet to do both these things, but a built-in option would be even better!

```css
.obsidian-sticky-heading {
    background-color: var(--background-primary); !important
}

.obsidian-sticky-heading::before {
    content: ""; !important
}
```

Thanks!
